INSERT INTO ciudad (codigo_ciudad, nombre_ciudad, codigo_region)
VALUES
	(1, 'San Francisco', 13),
    (2, 'Miami', 1),
    (3, 'Nueva York', 13),
    (4, 'Fuenlabrada', 2),
    (5, 'Madrid', 2),
    (6, 'San Lorenzo del Escorial', 2),
    (7, 'Montornes del valles', 3),
    (8, 'Santa cruz de Tenerife', 4),
    (9, 'Barcelona', 5),
    (10, 'Canarias', 6),
    (11, 'Sotogrande', 7),
    (12, 'Humanes', 2),
    (13, 'Getafe', 2),
    (14, 'Paris', 11),
    (15, 'Sydney', 8),
    (16, 'Londres', 9),
    (17, 'Barcelona', 3),
    (18, 'Boston', 10),
    (19, 'Londres', 12),
    (20, 'Sydney', 14),
    (21, 'Talavera de la Reina', 15),
    (22, 'Tokyo', 16);