INSERT INTO empleado (codigo_empleado, nombre, apellido1, apellido2, email, codigo_oficina, codigo_jefe, codigo_puesto, codigo_extension)
VALUES
	(1,'Marcos','Magaña','Perez','marcos@jardineria.es','TAL-ES',NULL,1,1),
	(2,'Ruben','López','Martinez','rlopez@jardineria.es','TAL-ES',1,2,2),
	(3,'Alberto','Soria','Carrasco','asoria@jardineria.es','TAL-ES',2,3,3),
	(4,'Maria','Solís','Jerez','msolis@jardineria.es','TAL-ES',2,4,4),
	(5,'Felipe','Rosas','Marquez','frosas@jardineria.es','TAL-ES',3,5,5),
	(6,'Juan Carlos','Ortiz','Serrano','cortiz@jardineria.es','TAL-ES',3,5,6),
	(7,'Carlos','Soria','Jimenez','csoria@jardineria.es','MAD-ES',3,6,7),
	(8,'Mariano','López','Murcia','mlopez@jardineria.es','MAD-ES',7,5,8),
	(9,'Lucio','Campoamor','Martín','lcampoamor@jardineria.es','MAD-ES',7,5,8),
	(10,'Hilario','Rodriguez','Huertas','hrodriguez@jardineria.es','MAD-ES',7,5,7),
	(11,'Emmanuel','Magaña','Perez','manu@jardineria.es','BCN-ES',3,6,9),
	(12,'José Manuel','Martinez','De la Osa','jmmart@hotmail.es','BCN-ES',11,5,10),
	(13,'David','Palma','Aceituno','dpalma@jardineria.es','BCN-ES',11,5,10),
	(14,'Oscar','Palma','Aceituno','opalma@jardineria.es','BCN-ES',11,5,10),
	(15,'Francois','Fignon','','ffignon@gardening.com','PAR-FR',3,6,11),
	(16,'Lionel','Narvaez','','lnarvaez@gardening.com','PAR-FR',15,5,12),
	(17,'Laurent','Serra','','lserra@gardening.com','PAR-FR',15,5,12),
	(18,'Michael','Bolton','','mbolton@gardening.com','SFC-USA',3,6,13),
	(19,'Walter Santiago','Sanchez','Lopez','wssanchez@gardening.com','SFC-USA',18,5,13),
	(20,'Hilary','Washington','','hwashington@gardening.com','BOS-USA',3,6,14),
	(21,'Marcus','Paxton','','mpaxton@gardening.com','BOS-USA',20,5,14),
	(22,'Lorena','Paxton','','lpaxton@gardening.com','BOS-USA',20,5,15),
	(23,'Nei','Nishikori','','nnishikori@gardening.com','TOK-JP',3,6,16),
	(24,'Narumi','Riko','','nriko@gardening.com','TOK-JP',23,5,16),
	(25,'Takuma','Nomura','','tnomura@gardening.com','TOK-JP',23,5,17),
	(26,'Amy','Johnson','','ajohnson@gardening.com','LON-UK',3,6,18),
	(27,'Larry','Westfalls','','lwestfalls@gardening.com','LON-UK',26,5,19),
	(28,'John','Walton','','jwalton@gardening.com','LON-UK',26,5,19),
	(29,'Kevin','Fallmer','','kfalmer@gardening.com','SYD-AU',3,6,20),
	(30,'Julian','Bellinelli','','jbellinelli@gardening.com','SYD-AU',29,5,21),
	(31,'Mariko','Kishi','','mkishi@gardening.com','SYD-AU',29,5,21);